name: CI
on:
  push:
  pull_request:

jobs:
  validate-json:
    name: Validate JSON
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: python eval/validate_all.py

  check-schema-sync:
    name: Check schema sync
    needs: validate-json
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: python eval/check_schema_sync.py
